#!/bin/bash

# Start fetch_quota.py in background if not running
pgrep -f "python3 /home/v/Projects/vlfstatus/fetch_quota.py" >/dev/null || python3 /home/v/Projects/vlfstatus/fetch_quota.py >/dev/null 2>&1 &

echo "{ \"version\": 1 }"
echo "["
echo "[]"

while true; do
	source ~/.cache/bar_colors.sh 2>/dev/null || { 
		COLOR_WIFI="#FF0055"
		COLOR_BAT_HIGH="#FF0055"
		COLOR_BAT_MID="#FF0055"
		COLOR_BAT_LOW="#FF0055"
		COLOR_TIME="#FF0055"
		COLOR_TEXT="#FFFFFF"
		COLOR_SEP="#0DCDCD"
	}

	DATETIME=$(date +"%d %a %H:%M:%S")
	WIFI_RAW=$(nmcli dev show wlp8s0 2>/dev/null | grep "GENERAL.CONNECTION" | sed -e "s/^GENERAL.CONNECTION:[ \t]*//")
	if [[ "$WIFI_RAW" == "--" || -z "$WIFI_RAW" ]]; then
		WIFI_ICON="󰤮 "
		WIFI_TEXT="Not connected"
	else
		WIFI_ICON="󰖩 "
		WIFI_TEXT="$WIFI_RAW"
	fi
	
	CAP=$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null || echo 100)
	if [[ ((CAP -gt 74)) ]]; then
		CAP_ICON=" "
		COLOR_BAT=$COLOR_BAT_HIGH
	elif [[ ((CAP -gt 49)) ]]; then
		CAP_ICON=" "
		COLOR_BAT=$COLOR_BAT_HIGH
	elif [[ ((CAP -gt 24)) ]]; then
		CAP_ICON=" "
		COLOR_BAT=$COLOR_BAT_MID
	elif [[ ((CAP -gt 10)) ]]; then
		CAP_ICON=" "
		COLOR_BAT=$COLOR_BAT_LOW
	else
		CAP_ICON=" "
		COLOR_BAT=$COLOR_BAT_LOW
	fi

	QUOTA_TEXT=""
	if [ -f ~/.cache/agy_quota.json ]; then
		G5H=$(grep -oP '"gemini_5h": "\K[0-9.]+' ~/.cache/agy_quota.json)
		C5H=$(grep -oP '"claude_5h": "\K[0-9.]+' ~/.cache/agy_quota.json)
		G_EPOCH=$(grep -oP '"gemini_5h_reset_epoch": \K[0-9]+' ~/.cache/agy_quota.json)
		C_EPOCH=$(grep -oP '"claude_5h_reset_epoch": \K[0-9]+' ~/.cache/agy_quota.json)
		
		if [ -n "$G5H" ] && [ -n "$C5H" ]; then
			NOW=$(date +%s)
			G_RESET="N/A"
			C_RESET="N/A"
			
			if [ -n "$G_EPOCH" ] && [ "$G_EPOCH" -gt 0 ]; then
				G_SEC=$((G_EPOCH - NOW))
				if [ $G_SEC -le 0 ]; then
					G_RESET="0s"
				else
					H=$((G_SEC / 3600))
					M=$(((G_SEC % 3600) / 60))
					S=$((G_SEC % 60))
					if [ $H -gt 0 ]; then
						G_RESET="${H}h${M}m"
					else
						G_RESET="${M}m${S}s"
					fi
				fi
			fi

			if [ -n "$C_EPOCH" ] && [ "$C_EPOCH" -gt 0 ]; then
				C_SEC=$((C_EPOCH - NOW))
				if [ $C_SEC -le 0 ]; then
					C_RESET="0s"
				else
					H=$((C_SEC / 3600))
					M=$(((C_SEC % 3600) / 60))
					S=$((C_SEC % 60))
					if [ $H -gt 0 ]; then
						C_RESET="${H}h${M}m"
					else
						C_RESET="${M}m${S}s"
					fi
				fi
			fi
			
			QUOTA_TEXT=" <span color='$COLOR_SEP'>//</span> <span color='$COLOR_WIFI'> </span><span color='$COLOR_TEXT'>${G5H}%</span><span color='$COLOR_SEP'> ${G_RESET}</span>  <span color='$COLOR_WIFI'> </span><span color='$COLOR_TEXT'>${C5H}%</span><span color='$COLOR_SEP'> ${C_RESET}</span>"
		fi
	fi
	
	BAR=" <span color='$COLOR_SEP'>//</span> <span color='$COLOR_WIFI'>$WIFI_ICON</span><span color='$COLOR_TEXT'>$WIFI_TEXT</span>$QUOTA_TEXT <span color='$COLOR_SEP'>//</span> <span color='$COLOR_BAT'>$CAP_ICON</span><span color='$COLOR_TEXT'>${CAP}%</span> <span color='$COLOR_SEP'>//</span> <span color='$COLOR_TIME'>󰃰 </span><span color='$COLOR_TEXT'>$DATETIME</span> "
	
	echo ",[{\"full_text\": \"$BAR\", \"markup\": \"pango\"}]"
	
	sleep 1
done

